minimum_pre_commit_version: 4.0.0
exclude: ^LICENSE|^README.md|^.clang-format|^.pre-commit-config.yaml|\.(html|csv|svg)$

ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:
  # pre-commit 基础检查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']

  # clang-format：C/C++ 代码格式化
  - repo: https://gitcode.com/pre-commit-clang/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        files: \.(c|h|cpp|hpp|cc|hh|cxx|hxx)$
        types_or: [c, c++]
        exclude: ^build/|^test/|^third_party/
