/*
 * Copyright (c) 2026 Huawei Technologies Co., Ltd. All Rights Reserved.
 *
 * Licensed under a modified version of the MIT license. See LICENSE in the project root for license information.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

DEFINE_WRAPPER(8, s8, int8_t, svint8_t);
DEFINE_WRAPPER(8, u8, uint8_t, svuint8_t);
DEFINE_WRAPPER(16, s16, int16_t, svint16_t);
DEFINE_WRAPPER(16, u16, uint16_t, svuint16_t);
DEFINE_WRAPPER(32, s32, int32_t, svint32_t);
DEFINE_WRAPPER(32, u32, uint32_t, svuint32_t);
DEFINE_WRAPPER(64, s64, int64_t, svint64_t);
DEFINE_WRAPPER(64, u64, uint64_t, svuint64_t);
DEFINE_WRAPPER(16, f16, __fp16, svfloat16_t);
DEFINE_WRAPPER(16, bf16, __bf16, svbfloat16_t);
DEFINE_WRAPPER(32, f32, float, svfloat32_t);
DEFINE_WRAPPER(64, f64, double, svfloat64_t);
#undef DEFINE_WRAPPER
